changeLanguage = "Language is successfully changed."
delete = "Delete â“"
enterOrderName = "What is the name of your order?"
enterTrackingNumber = "What is the tracking number of your order?"
error = "Something went wrong. ğŸ†˜"
greetings = "Hi there! ğŸ‘‹\nStart monitoring your orders by typing:\n/add_tracking"
noTrackings = "You have 0ï¸âƒ£ trackings added.\nCreate an order using command:\n/add_tracking"
notEnoughArgumentsForTracking = "Please specify arguments in format:\n `/add_tracking -v=\"YOUR_TRACKING_NUMBER\" -n=\"NAME_OF_ORDER\"`"
requestLanguageChange = "Which language do you prefer?"
trackingAdded = "Tracking was successfully added. âœ…\nI will notify you about its changes ASAP."
trackingInfo = "Name: *{{.Name}}*\nStatus: *{{.Status}}*\nWeight: *{{.Weight}}*\nTracking: *{{.Value}}*"
trackingUpdated = "â—ï¸â—ï¸â—ï¸ Your order status has been changed â—ï¸â—ï¸â—ï¸"
